# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inframirror-backend
  namespace: inframirror
  labels:
    app: inframirror-backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inframirror-backend
  template:
    metadata:
      labels:
        app: inframirror-backend
        tier: backend
    spec:
      containers:
      - name: backend
        image: registry.kapitalbank.az/v1/repositories/baseimages/inframirror/inframirror-backend:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: MONGODB_URI
          value: "mongodb://10.0.93.60:27017,10.0.93.59:27017/?replicaSet=inframirror"
        - name: MONGODB_DATABASE
          value: "inframirror_inventory"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: inframirror-backend-service
  namespace: inframirror
  labels:
    app: inframirror-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: inframirror-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inframirror-frontend
  namespace: inframirror
  labels:
    app: inframirror-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inframirror-frontend
  template:
    metadata:
      labels:
        app: inframirror-frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: registry.kapitalbank.az/v1/repositories/baseimages/inframirror/inframirror-front:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: inframirror-frontend-service
  namespace: inframirror
  labels:
    app: inframirror-frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: inframirror-frontend